### ISSUE TITLE
Kerbalism and Telemachus reborn antenna power use

### ISSUE THREAD

**Issue by tomimas** [TeleIO/Telemachus-1#13]
KSP 1.6.1
Kerbalism: 1.2.1 (https://github.com/steamp0rt/Kerbalism)
Telemachus 1.6.22.F2

I don't know if this is an issue or a feature, but the power use of antennas is rather hefty, when these two mods are combined. Part says 1.8/min, but Kerbalism says 12.020/s. Everything is fine when only either one is installed.

[Just OKTO](https://suuronen.eu/blog/wp-content/uploads/2019/04/kerbalism_and_telemachus-1.png)

Telemachus uses some sort of antenna bitRate (factor of per thousands) to calculate it's power need. First I thought this is somewhat expected until I investigated it further. Maybe Kerbalism uses same sort of technique. Because, simply adding a single HG-5 Relay Antenna to the OKTO causes the power use to be over 50/s. So double multiplication is happening somewhere. I have no clue, what can and cannot be done with mods. Could it be possible to introduce somewhere that if Telemachus is installed use only Kerbalism power use calculations?

I did contact the the other modder also, as I would like to see these two awesome mods to be able to work together, and now are not.

**Comment by SirMortimer** [comment]
I won't look at this until #12 is fixed.

**Comment by StoneBlue** [comment]
> 
> 
> I won't look at this until #12 is fixed.

Seems to be fixed nao.
Dont know if the issue with Kerbalism is still valid, tho? vOv

**Comment by SirMortimer** [comment]
Loos good to me now. Seems to be fixed with Kerbalism 3.2 (probably 3.1, maybe even 3.0)
See https://github.com/Kerbalism/Kerbalism/issues/373#issuecomment-567559327

**Comment by sidrus** [comment]
Should I close this ticket?  From the previous comments, it seems like this is resolved.

**Comment by StoneBlue** [comment]
I'll take a look at this in the next couple days, to see if its still an issue with the latest Telemachus, and mebbe we can close it

**Comment by StoneBlue** [comment]
So I did try to look at this about a week ago. I couldnt find an easy way to isolate specific EC usage as far as the Kerbalism vs Telemachus antennas go. Granted, I am a Kerbalism noob, and have hardly ever used the mod, much less lately.

There were a few issues, that I think are related to "stock" Telemachus that should probably be looked at first, IMHO, before investigating compatability with support for other mods.

Not to discourage anyone from posting any info, details, or behaviour that they see with this Kerbalism issue, that either to confirm it *still* is an issue, or details that mihgt help point to what the issue could be.

**Comment by SolAstrius** [comment]
Kerbalism resolved this on their side in versions 3.1–3.2 — they stopped incorrectly draining EC from non-Kerbalism antenna parts. If you're still seeing this, make sure you're on Kerbalism 3.2 or later. Closing as resolved upstream.
